apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hdp
  region: us-east-1
  version: "1.18"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        # TODO: change the policy to https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.2/docs/install/iam_policy.json
        - arn:aws:iam::aws:policy/PowerUserAccess

addons:
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["all"]

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

nodeGroups:
  - name: k8s-workers-us-east-1a
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 5
    availabilityZones: ["us-east-1a"]
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true

  - name: k8s-workers-us-east-1b
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 5
    availabilityZones: ["us-east-1b"]
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true

  - name: k8s-workers-us-east-1c
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 5
    availabilityZones: ["us-east-1c"]
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true
